In [1]:
import numpy as np

A = np.random.random((4,4))
A = A.T*A # make it symmetric for real eigen_values
print A
eigen_values, _ = np.linalg.eig(A)
eigen_values = np.sort(eigen_values)
print eigen_values

[[ 0.01129525  0.17955466  0.14911626  0.53245047]
 [ 0.17955466  0.39175899  0.1026354   0.12613663]
 [ 0.14911626  0.1026354   0.62446565  0.80088057]
 [ 0.53245047  0.12613663  0.80088057  0.01250251]]
[-0.73281098  0.01694186  0.38983396  1.36605757]


In [2]:
def qr_one(A):
    Q, R = np.linalg.qr(A)
    return np.dot(R, Q)

def qr_iterations(A):
    B = A.copy(); e = np.ones(eigen_values.shape)
    while np.linalg.norm(e):
        B = qr_one(B)
        e = np.around(np.sort(np.diagonal(B))-eigen_values, 3)
        print e
        
qr_iterations(A)

[ 0.747  0.157 -0.114 -0.791]
[ 0.562 -0.    -0.252 -0.31 ]
[ 0.216 -0.    -0.117 -0.099]
[ 0.067 -0.    -0.038 -0.03 ]
[ 0.02   0.    -0.011 -0.009]
[ 0.006  0.    -0.003 -0.002]
[ 0.002  0.    -0.001 -0.001]
[ 0.  0. -0. -0.]


In [3]:
def unique_eig_decomposition():
    X = np.array([[1,1,1],[0,0,1],[-1,1,5]]).T # eigenvectors
    L = np.diag([7,4,3]) # eigenvalues
    print np.dot(np.dot(X,L),np.linalg.inv(X))
    
    # switch first 2 columns
    E = np.array([
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])
    X = np.dot(X, E)
    L = np.diag([4,7,3])
    B = np.dot(np.dot(X,L),np.linalg.inv(X))
    print B
    
    # A = X L X^(-1) is unique decomposition
    # eigen values & vectors tell everything about A
    
unique_eig_decomposition()

[[ 5.  2.  0.]
 [ 2.  5.  0.]
 [ 4. -1.  4.]]
[[ 5.  2.  0.]
 [ 2.  5.  0.]
 [ 4. -1.  4.]]


In [5]:
def fibonacci_eig():
    Q = np.array([[1,1],[1,0]])
    evals, X = np.linalg.eig(Q)
    # print np.dot(np.dot(X,np.diag(evals)),np.linalg.inv(X))
    return evals
    
def fibonacci2(n):
    return np.round(np.linalg.matrix_power(np.array([[1,1],[1,0]], dtype='float64'),n)[0,0],1)

def fibonacci1(n):
    if n<2: return 1.
    L, X = np.linalg.eig(np.array([[1,1],[1,0]]))
    Y = np.dot(X, np.diag(L**n))
    Y = np.dot(Y, X.T)
    return np.round(Y[0,0],1)
    
# print fibonacci_eig()
    
def fibonacci(n):
    A = np.array([[ 0.85065081, -0.52573111],
                  [ 0.52573111,  0.85065081]])
    L = np.array([ 1.61803399, -0.61803399])
    return np.round(np.dot(np.dot(A, np.diag(L**n)), A.T)[0,0],1)

print [fibonacci(i) for i in xrange(10)]
print [fibonacci(i) for i in xrange(0,1600,200)]

# Also ref "generating matrix for a recurrence relation"
# http://math.stackexchange.com/questions/124178/generating-matrix-for-a-recurrence-relation

[1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0, 55.0]
[1.0, 4.5397376607296954e+41, 2.8481238723127974e+83, 1.7868454519317291e+125, 1.1210245102494092e+167, 7.0330422321714219e+208, 4.4123640997378306e+250, 2.7682127173355929e+292]
